### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by DavidLibeau** [francoismari/elyze#1]
The repository doesn't have any License. Could you add one?

**Comment by Exagone313** [comment]
Also it needs a copyright notice, bundling a license file in a repo is not enough.

**Comment by ponceto** [comment]
Bonjour,

Le code de l'application étant ouvert (et la démarche mérite d'être saluée), il manque cependant les termes de la licence.

C'est un point crucial, permettant de savoir si le code est juste ouvert ou répond bien aux définitions de OpenSource ou Logiciel Libre, permettant ainsi de savoir si l'on peut contribuer au logiciel, si le code peut-être forké, modifié, redistribué, etc ...

Au choix, une licence GPL-v2, BSD, MIT, Apache, etc ...

**Comment by antoninhrlt** [comment]
En plus d'une licence, l'ajout d'une description, et d'instructions/informations sur le README.md ne serait pas de refus.

**Comment by StephaneBranly** [comment]
Une license a été ajoutée depuis (commit 7871e7113d3f0c4101b5c1edb2dd57cd35d898ba)
Neanmoins le choix de la license est remis en cause dans l'issue #20

**Comment by Gouvernathor** [comment]
Le problème (en tant que tel) a été réglé, une autre issue a pris la main pour des questions sur la licence appliquée. Cette issue devrait être fermée.

**Comment by DavidLibeau** [comment]
J'aurais aimé que ça soit les auteur·rice·s qui gèrent les issues, mais ça n'a pas l'air d'être le cas… Je ferme donc l'issue pour elleux.

**Comment by ponceto** [comment]
> J'aurais aimé que ça soit les auteur·rice·s qui gèrent les issues, mais ça n'a pas l'air d'être le cas… Je ferme donc l'issue pour elleux.

Étrange que cela ne soit pas les auteurs qui gères les issues, non ?
